name: libclash_vpn_service
version: 0.12.15
description: A Flutter plugin for libclash VPN services.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.0
  plugin_platform_interface: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nebula.libclash_vpn_service
        pluginClass: LibclashVpnServicePlugin
      ios:
        pluginClass: LibclashVpnServicePlugin
      linux:
        pluginClass: LibclashVpnServicePlugin
      macos:
        pluginClass: LibclashVpnServicePlugin
      windows:
        pluginClass: LibclashVpnServicePlugin
